DELETE ELEMENT

//PART 1
LOCATE: NODE W/ ELEMENT + ITS PARENT NODE

//PART 2
ASSIGN: NODE W/ ELEMENT - TO CURRENT + ITS PARENT NODE - TO PARENT

//PART 3 - SPECIAL CASE
//CASE 1 : IF CURRENT HAS A RIGHT NODE
CONNECT RIGHT TO PARENT

//CASE 2 : IF CURRENT HAS A LEFT NODE  : 
LOCATE RIGHTMOST"CURRENT NODE(DELETE ELEMENT)- LEFT NODE - RIGHT NODE" - THAN REPLACE CURRENT WITH RIGHTMOST
PARENTOFRIGHTMOST CONNECT TO CURRENT "ON LEFT"
LEFTCHILDOFRIGHMOST CONNECT TO PARENTOFRIGHTMOST "ON RIGHT"

EXAMPLES:
IF DELETE W/ LEFT AND RIGHMOST W/ NO RIGHTMOST CHILDREN - JUST REPLACE "CURRENT"DELETE WITH RIGHTMOST
IF DELETE W/ NO CHILDREN - JUST DELETE
IF DELETE W/ LEFT & RIGHT - REPLACE "CURRENT"DELETE W/ LEFT

