TREE TRAVESAL "VISIT EACH NODE"

INORDER 		: LEFT, CURRENT, RIGHT
POSTORDER 		: LEFT, RIGHT, CURRENT
PREORDER 		: CURRENT, LEFT, RIGHT
BREADTH-FIRST	: ROOT, CHILDREN"LEFT-RIGHT"  //LEVEL BY LEVEL
