//5
------DELETE ELEMENT------

//PART 1
LOCATE: NODE W/ ELEMENT + ITS PARENT NODE

//PART 2
ASSIGN: NODE W/ ELEMENT - TO CURRENT + ITS PARENT NODE - TO PARENT

//PART 3 - SPECIAL CASE
CASE 1 : IF CURRENT HAS A RIGHT NODE
	CONNECT RIGHT TO PARENT

CASE 2 : IF CURRENT HAS A LEFT NODE  : 
	(1)LOCATE RIGHTMOST"CURRENT NODE(DELETE ELEMENT)- LEFT NODE - RIGHT NODE" - THEN REPLACE CURRENT WITH RIGHTMOST

	(2)PARENTOFRIGHTMOST CONNECT TO CURRENT "ON LEFT"

	(3)LEFTCHILDOFRIGHMOST CONNECT TO PARENTOFRIGHTMOST "ON RIGHT"

EXAMPLES:
IF DELETE W/ LEFT AND RIGHMOST W/ NO RIGHTMOST CHILDREN - JUST REPLACE "CURRENT" WITH RIGHTMOST

IF DELETE W/ NO CHILDREN - JUST DELETE

IF DELETE W/ LEFT(NO CHILDREN) & RIGHT - REPLACE "CURRENT" W/ LEFT

