//4
----THEORY----

TREE TRAVESAL "VISIT EACH NODE"

INORDER 		: LEFT, CURRENT, RIGHT  "current in the middle"

POSTORDER 		: LEFT, RIGHT, CURRENT

PREORDER 		: CURRENT, LEFT, RIGHT

BREADTH-FIRST	: ROOT, CHILDREN"LEFT-RIGHT"  //LEVEL BY LEVEL

